export const LINKS = [
  {
    id: 1,
    borderColor: "rgba(0,0,0,0.25)",
    borderWidth: "5",
    borderStyle: "solid",
    icon: "twitter",
    iconColor: "rgba(255,255,255,1)",
    backgroundColor: "rgba(26,166,233,1)",
    iconSize: "5",
    roundness: "50%",
    url: "https://some-website.com/my-social-media-url",
    size: "38",
  },
  {
    id: 2,
    borderColor: "rgba(0,0,0,0.25)",
    borderWidth: "5",
    borderStyle: "solid",
    icon: "facebook",
    iconColor: "rgba(255,255,255,1)",
    backgroundColor: "rgba(26,166,233,1)",
    iconSize: "5",
    roundness: "50%",
    url: "https://some-website.com/my-social-media-url",
    size: "38",
  },
  {
    id: 3,
    borderColor: "rgba(0,0,0,0.25)",
    borderWidth: "5",
    borderStyle: "solid",
    icon: "instagram",
    iconColor: "rgba(255,255,255,1)",
    backgroundColor: "rgba(26,166,233,1)",
    iconSize: "5",
    roundness: "50%",
    url: "https://some-website.com/my-social-media-url",
    size: "38",
  },
  {
    id: 4,
    borderColor: "rgba(0,0,0,0.25)",
    borderWidth: "5",
    borderStyle: "solid",
    icon: "youtube",
    iconColor: "rgba(255,255,255,1)",
    backgroundColor: "rgba(26,166,233,1)",
    iconSize: "5",
    roundness: "50%",
    url: "https://some-website.com/my-social-media-url",
    size: "38",
  },
];
